version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    links:
      - mongo
    build:
      context: ./
      dockerfile: Docker/docker-backend/Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./
      dockerfile: Docker/docker-frontend/Dockerfile
    ports:
      - "80:80"

  # rule:
  #   build:
  #     context: ./
  #     dockerfile: Docker/docker-json-rule-editor/Dockerfile
  #   ports:
  #     - "8081:8081"